{
  "code":0,
  "msg":"",
  "roledata":[
    {"name":"后端工程师"},
    {"name":"前端工程师"},
    {"name":"UI工程师"},
    {"name":"运维工程师"}
  ],
  "postdata":[
    {"name":"开发岗"},
    {"name":"运维岗"},
    {"name":"管理岗"}
  ]
}